development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fisherman_devel
  pool: 5
  username: root
  password: fusion87
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: fisherman
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000